server:
  port: 9988
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test_db
    username: root
    password: 1234

jwt:
  secretKey: qwertyasdfqwerty
  permission:
      permit-all-urls:
        -/api/member/login
        -/api/member/join